spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
#    alicloud:
#      access-key: LTAI5tK2J2G7wpqgeoRrGRiR
#      secret-key: JQF8NEs8WvbJyCC1udMgy6KLwqnMuQ
#      oss:
#        endpoint: oss-cn-shanghai.aliyuncs.com
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 10000
logging:
  level:
    com.aiguigu.gulimall.product.dao: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug







